#Lifecyle create->join->start->out->end
Party:
  #派对类别
  test:
    #开始游戏的人数
    StartAmount: 2
    #倒计时的时间
    StartSecond: 60
    #加速倒计时的人数
    AccelerateAmount: 3
    #加速到几秒
    AccelerateSecond: 10
    #留下一个人时结束游戏
    LeaveAmount: 1
    #触发器
    Trigger:
      PlayerJoinPartyEvent:
        NONSELF: 有人加入了游戏
        SELF: 你加入了游戏
      PlayerLeavePartyEvent:
        NONSELF: 有人退出了游戏
        SELF: 你退出了游戏
      PartyStartEvent:
        ALL: 游戏开始
      PlayerOutEvent:
        SELF: 你被淘汰了
        NONSELF: 有人被淘汰了
      PartyEndEvent:
        ALL: 游戏结束
#    Reward:
#      Winner: 胜者奖励
#      30%: 前百分之30奖励
#      50%: 前百分之30奖励
#      100%: 参与奖励